hl.on("hyprland.start", function()
	hl.exec_cmd("xdg-desktop-portal")
	hl.exec_cmd("xdg-desktop-portal-gtk")
	hl.exec_cmd("pipewire")
	hl.exec_cmd("wireplumber")
	hl.exec_cmd("pipewire-pulse")
	hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
	hl.exec_cmd("~/.config/hypr/hyprpaper.conf.d/randomwallpaper.sh")
	hl.exec_cmd("sleep 2 && waybar")
	-- hl.exec_cmd("hyprsunset")
end)
