windowrule {                                                                                       
        name = opacity-scrcpy                                                                      
        match:class = scrcpy                                                                       
                                                                                                   
        fullscreen = 1                                                                             
                                                                                                   
        opacity = 1                                                                                
}   
windowrule {                                                                                       
        name = opacity-gnome                                                                       
        match:class = steam_app_480430                                                             
                                                                                                   
        fullscreen = 1                                                                             
                                                                                                   
        opacity = 1                                                                                
}                                                                                                  
windowrule {                                                                                       
        name = opacity-sledding-game                                                               
        match:class = steam_app_4029310                                                            
                                                                                                   
        fullscreen = 1                                                                             
                                                                                                   
        opacity = 1                                                                                
}                                                                                                  
windowrule {                                                                                       
        name = opacity-libreoffice-impress                                                         
        match:class = libreoffice-impress                                                          
                                                                                                   
        opacity = 1                                                                                
}

windowrule {
	name = opacity-fullscreen
	match:fullscreen = true

	opacity = 1
}
