exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = systemctl --user restart xdg-desktop-portal
exec-once = ~/.config/hypr/hyprpaper.conf.d/randomwallpaper.sh
exec-once = waybar
exec-once = hyprsunset
