exec-once = xdg-desktop-portal
exec-once = xdg-desktop-portal-gtk
exec-once = pipewire
exec-once = wireplumber
exec-once = pipewire-pulse
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = ~/.config/hypr/hyprpaper.conf.d/randomwallpaper.sh
exec-once = sleep 2 && waybar
#exec-once = hyprsunset
