bind = $mainMod, E, exec, $terminal, -e, $fileManager
bind = $mainMod, Return, exec, $terminal
bind = $mainMod, C, killactive
bind = , Print, exec, grim -g "$(slurp)" - | wl-copy

bind = $mainMod ALT, S, exec, shutdown now
bind = $mainMod ALT, L, exec, hyprlock
bind = $mainMod ALT, O, exec, hyprctl dispatch exit

bind = $mainMod, T, exec, /home/lucas/.config/hypr/toggle_opacity.sh

bind = $mainMod CTRL, D, exec, discord
bind = $mainMod CTRL, B, exec, helium
bind = $mainMod CTRL SHIFT, H, exec, heroic
bind = $mainMod CTRL, R, exec, flatpak run org.vinegarhq.Sober
bind = $mainMod CTRL, M, exec, env LD_PRELOAD=/usr/lib/spotify-adblock.so spotify
bind = $mainMod CTRL, S, exec, steam

bind = ALT SHIFT, D, workspace, $discordWP
bind = ALT SHIFT, M, workspace, $musicWP
bind = ALT SHIFT, G, workspace, $gameWP
bind = ALT SHIFT, B, workspace, $browserWP
bind = ALT SHIFT, C, workspace, $codeWP

bind = $mainMod, H, movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, r

bind = $mainMod, ampersand, workspace, 1
bind = $mainMod, eacute, workspace, 2
bind = $mainMod, quotedbl, workspace, 3
bind = $mainMod, apostrophe, workspace, 4
bind = $mainMod, parenleft, workspace, 5
bind = $mainMod, minus, workspace, 6
bind = $mainMod, egrave, workspace, 7
bind = $mainMod, underscore, workspace, 8
bind = $mainMod, ccedilla, workspace, 9
bind = $mainMod, agrave, workspace, 10

bind = $mainMod CTRL, L, movewindow, r
bind = $mainMod CTRL, K, movewindow, u
bind = $mainMod CTRL, J, movewindow, d
bind = $mainMod CTRL, H, movewindow, l

bindm = $mainMod, mouse:272, movewindow
