bind = $mainMod, E, exec, $fileManager
bind = $mainMod, Return, exec, $terminal
bind = $mainMod, C, killactive
bind = , Print, exec, $HOME/.config/hypr/scripts/screenshot.sh
bind = $mainMod, F, fullscreen

bind = $mainMod ALT, S, exec, hyprshutdown --post-cmd "loginctl poweroff now"
bind = $mainMod ALT, R, exec, hyprshutdown --post-cmd "loginctl reboot"
bind = $mainMod ALT, L, exec, hyprlock
bind = $mainMod ALT, O, exec, hyprctl dispatch exit

bind = $mainMod, T, exec, $HOME/.config/hypr/scripts/toggle_opacity.sh

bind = $mainMod CTRL, D, exec, discord --enable-features=UseOzonePlatform --ozone-platform=wayland
bind = $mainMod CTRL, B, exec, helium-browser
bind = $mainMod CTRL, E, exec, env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only heroic
bind = $mainMod CTRL, R, exec, flatpak run org.vinegarhq.Sober
bind = $mainMod CTRL, M, exec, env LD_PRELOAD=/usr/lib/spotify-adblock.so spotify
bind = $mainMod CTRL, S, exec, steam

bind = ALT SHIFT, D, workspace, $discordWP
bind = ALT SHIFT, M, workspace, $musicWP
bind = ALT SHIFT, G, workspace, $gameWP
bind = ALT SHIFT, B, workspace, $browserWP
bind = ALT SHIFT, C, workspace, $codeWP

bind = $mainMod, H, movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, r

bind = $mainMod, ampersand, workspace, 1
bind = $mainMod, eacute, workspace, 2
bind = $mainMod, quotedbl, workspace, 3
bind = $mainMod, apostrophe, workspace, 4
bind = $mainMod, parenleft, workspace, 5
bind = $mainMod, minus, workspace, 6
bind = $mainMod, egrave, workspace, 7
bind = $mainMod, underscore, workspace, 8
bind = $mainMod, ccedilla, workspace, 9
bind = $mainMod, agrave, workspace, 10

bind = $mainMod CTRL, L, movewindow, r
bind = $mainMod CTRL, K, movewindow, u
bind = $mainMod CTRL, J, movewindow, d
bind = $mainMod CTRL, H, movewindow, l

bindm = $mainMod, mouse:272, movewindow
