monitor = HDMI-A-1, preferred, 0x0, auto
monitor = eDP-1, preferred, 1920x0, auto

workspace = $discordWP, monitor:eDP-1, default:true, persistent:true
workspace = $gameWP, monitor:HDMI-A-1, default:true, persistent:true
workspace = $musicWP, monitor:eDP-1, default:false, persistent:true
workspace = $browserWP, monitor:eDP-1, default:false, persistent:true
workspace = $codeWP, monitor:HDMI-A-1, default:false, persistent:true

workspace = $gameWP, border:false, rounding:false

windowrule = match:class discord, workspace $discordWP
windowrule = match:class spotify, workspace $musicWP
windowrule = match:class heroic, workspace $gameWP
windowrule = match:class brave-browser, workspace $browserWP
windowrule = match:class helium-browser, workspace $browserWP
windowrule = match:class sober, workspace $gameWP
windowrule = match:class org.vinegarhq.Sober, workspace $gameWP

windowrule = tag +toggle_opacity, match:class *
windowrule = tag toggle_opacity, match:class *

exec-once = [workspace $discordWP] discord
exec-once = [workspace $musicWP] env LD_PRELOAD=/usr/lib/spotify-adblock.so spotify
exec-once = [workspace $gameWP] env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only heroic
exec-once = [workspace $browserWP] helium-browser
exec-once = [workspace $codeWP] $terminal
