monitor = HDMI-A-1, preferred, 0x0, auto
monitor = eDP-1, preferred, 1920x0, auto

workspace = $discordWP, monitor:eDP-1, default:true, persistent:true
workspace = $gameWP, monitor:HDMI-A-1, default:true, persistent:true
workspace = $musicWP, monitor:eDP-1, default:false, persistent:true
workspace = $browserWP, monitor:eDP-1, default:false, persistent:true
workspace = $codeWP, monitor:HDMI-A-1, default:false, persistent:true

windowrule = match:class discord, workspace $discordWP
windowrule = match:class spotify, workspace $musicWP
windowrule = match:class heroic, workspace $gameWP
windowrule = match:class brave-browser, workspace $browserWP
windowrule = match:class helium, workspace $browserWP
windowrule = match:class sober, workspace $gameWP
windowrule = match:class org.vinegarhq.Sober, workspace $gameWP
windowrule = match:class steam_app_7d690c122fde4c60bed85405f343ad10, workspace $gameWP  # Genshin I    mpact launcher

windowrule = tag +toggle_opacity, match:class *
windowrule = tag toggle_opacity, match:class *

exec-once = [workspace $discordWP] discord
exec-once = [workspace $musicWP] env LD_PRELOAD=/usr/lib/spotify-adblock.so spotify
exec-once = [workspace $gameWP] heroic
exec-once = [workspace $browserWP] helium
exec-once = [workspace $codeWP] $terminal
