windowrule {                                                                                       
        name = opacity-scrcpy                                                                      
        match:class = scrcpy                                                                       
                                                                                                   
        fullscreen = 1                                                                             
                                                                                                   
        opacity = 1                                                                                
}   
windowrule {                                                                                       
        name = opacity-gnome                                                                       
        match:class = steam_app_480430                                                             
                                                                                                   
        fullscreen = 1                                                                             
                                                                                                   
        opacity = 1                                                                                
}                                                                                                  
windowrule {                                                                                       
        name = opacity-sledding-game                                                               
        match:class = steam_app_4029310                                                            
                                                                                                   
        fullscreen = 1                                                                             
                                                                                                   
        opacity = 1                                                                                
}                                                                                                  
windowrule {                                                                                       
        name = opacity-libreoffice-impress                                                         
        match:class = libreoffice-impress                                                          
                                                                                                   
        opacity = 1                                                                                
}
windowrule {                                                                                       
        name = opacity-tf_linux64
        match:class = tf_linux64
                                                                                                   
        opacity = 1
	fullscreen = true
}

windowrule {
	name = opacity-fullscreen
	match:fullscreen = true

	opacity = 1
}


#windowrulev2 = fullscreen,class:^steam_app_\d+$
#windowrulev2 = monitor HDMI-1-1,class:^steam_app_\d+$
#windowsrulev2 = workspace $gameWP,class:^steam_app_\d+$
windowrule = match:class ^steam_app_\d+$, fullscreen true, monitor HDMI-A-1, workspace $gameWP


